"""Editando tabela Horario - Nova

Revision ID: 024d7889e8dc
Revises: 377b746ee925
Create Date: 2025-02-08 16:00:29.019591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024d7889e8dc'
down_revision = '377b746ee925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_rota', sa.Integer(), nullable=False),
    sa.Column('horario', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['id_rota'], ['rota.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horario')
    # ### end Alembic commands ###
