"""Renomeando tabela usuario

Revision ID: 086b3eacc07a
Revises: 
Create Date: 2025-02-02 17:00:06.220861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086b3eacc07a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=20), nullable=False),
    sa.Column('senha', sa.String(length=32), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('online', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.drop_table('Usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('login', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('perfil', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('online', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Usuario_pkey'),
    sa.UniqueConstraint('login', name='Usuario_login_key')
    )
    op.drop_table('usuario')
    # ### end Alembic commands ###
