"""Adicionando tabela Parada

Revision ID: 28927924e3c3
Revises: 0efc737d9a35
Create Date: 2025-02-05 19:55:03.267236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28927924e3c3'
down_revision = '0efc737d9a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parada')
    # ### end Alembic commands ###
