"""Recriando Usuario

Revision ID: 29c163625d99
Revises: d75adc407f70
Create Date: 2025-02-19 20:13:40.053961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c163625d99'
down_revision = 'd75adc407f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.Integer(), nullable=False),
    sa.Column('senha', sa.String(length=32), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('online', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['login'], ['rota.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
