"""Adicionando tabela historico

Revision ID: 353e5a63bcd7
Revises: 086b3eacc07a
Create Date: 2025-02-04 21:47:10.454136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353e5a63bcd7'
down_revision = '086b3eacc07a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('rota', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico')
    # ### end Alembic commands ###
