"""Editando tabela Historico

Revision ID: 377b746ee925
Revises: 407287dc2843
Create Date: 2025-02-08 15:05:48.450504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '377b746ee925'
down_revision = '407287dc2843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_rota', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('data_registro', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('posicao', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('mensagem', sa.String(length=15), nullable=True))
        batch_op.create_foreign_key(None, 'parada', ['posicao'], ['id'])
        batch_op.create_foreign_key(None, 'rota', ['id_rota'], ['id'])
        batch_op.drop_column('rota')
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rota', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mensagem')
        batch_op.drop_column('posicao')
        batch_op.drop_column('data_registro')
        batch_op.drop_column('id_rota')

    # ### end Alembic commands ###
