"""Adicionando tabela Viagem

Revision ID: 3e747b0dc4a6
Revises: 793399da2b20
Create Date: 2025-02-05 21:19:59.600488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e747b0dc4a6'
down_revision = '793399da2b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_rota', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_rota'], ['rota.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viagem')
    # ### end Alembic commands ###
