"""Adicionando tabela Horario

Revision ID: 407287dc2843
Revises: 3e747b0dc4a6
Create Date: 2025-02-08 14:37:52.509792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407287dc2843'
down_revision = '3e747b0dc4a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horario',
    sa.Column('id_rota', sa.Integer(), nullable=False),
    sa.Column('horario', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['id_rota'], ['rota.id'], ),
    sa.PrimaryKeyConstraint('id_rota')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horario')
    # ### end Alembic commands ###
