"""Editando tabelas

Revision ID: 5aa4befe2e4b
Revises: 024d7889e8dc
Create Date: 2025-02-18 21:18:47.915851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5aa4befe2e4b'
down_revision = '024d7889e8dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viagem')
    with op.batch_alter_table('rota_parada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rota_parada', schema=None) as batch_op:
        batch_op.drop_column('id')

    op.create_table('viagem',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_rota', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data_fim', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_rota'], ['rota.id'], name='viagem_id_rota_fkey'),
    sa.PrimaryKeyConstraint('id', name='viagem_pkey')
    )
    # ### end Alembic commands ###
