"""Adicionando tabela RotaParada

Revision ID: 793399da2b20
Revises: 28927924e3c3
Create Date: 2025-02-05 20:25:56.319429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793399da2b20'
down_revision = '28927924e3c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rota_parada',
    sa.Column('id_rota', sa.Integer(), nullable=False),
    sa.Column('id_parada', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_parada'], ['parada.id'], ),
    sa.ForeignKeyConstraint(['id_rota'], ['rota.id'], ),
    sa.PrimaryKeyConstraint('id_rota', 'id_parada')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rota_parada')
    # ### end Alembic commands ###
