"""Recriando RotaParada

Revision ID: 793fb68b23ad
Revises: 5aa4befe2e4b
Create Date: 2025-02-18 21:25:25.616203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793fb68b23ad'
down_revision = '5aa4befe2e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rota_parada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_rota', sa.Integer(), nullable=False),
    sa.Column('id_parada', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_parada'], ['parada.id'], ),
    sa.ForeignKeyConstraint(['id_rota'], ['rota.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_rota', 'id_parada')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rota_parada')
    # ### end Alembic commands ###
