"""Criacao de Tabelas

Revision ID: b56196d5a2a2
Revises: 
Create Date: 2025-03-16 20:23:42.476931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56196d5a2a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('rota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_rota', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['id_rota'], ['rota.id'], ),
    sa.ForeignKeyConstraint(['posicao'], ['parada.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_rota', sa.Integer(), nullable=False),
    sa.Column('horario', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['id_rota'], ['rota.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rota_parada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_rota', sa.Integer(), nullable=True),
    sa.Column('id_parada', sa.Integer(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_parada'], ['parada.id'], ),
    sa.ForeignKeyConstraint(['id_rota'], ['rota.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.Integer(), nullable=False),
    sa.Column('senha', sa.String(length=32), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('online', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['login'], ['rota.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_rota', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_rota'], ['rota.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viagem')
    op.drop_table('usuario')
    op.drop_table('rota_parada')
    op.drop_table('horario')
    op.drop_table('historico')
    op.drop_table('rota')
    op.drop_table('parada')
    # ### end Alembic commands ###
