"""Recriando Viagem - Remover db.relationship

Revision ID: d75adc407f70
Revises: 5084ba44056f
Create Date: 2025-02-18 21:50:49.482314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75adc407f70'
down_revision = '5084ba44056f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_rota', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_rota'], ['rota.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viagem')
    # ### end Alembic commands ###
